# Optimitzacio
OPT=-g -Wall

# Tot:
all : polexpl placaexp placacn

# Utilitats:
# - Polinomi explicit
polexpl : polexpl.c grRDF.o grRDF.h
	gcc -o polexpl $(OPT) polexpl.c grRDF.o -lm
# - Placa explicita
placaexp : placaexp.c grRDF.o grRDF.h
	gcc -o placaexp $(OPT) placaexp.c grRDF.o -lm
# - Placa Crank-Nicolson
placacn : placacn.c grRDF.o grRDF.h
	gcc -o placacn $(OPT) placacn.c grRDF.o -lm

# Biblioteca
grRDF.o : grRDF.c grRDF.h
	gcc -c $(OPT) grRDF.c

# Neteja
clean :
	rm -f *.o
realclean : clean
	rm -f polexpl placaexp placacn
